import type {Language} from '../types'

export const translations: Record<Language, Record<string, string>> = {
    es: {
        title: 'HeroVerse Multiverse',
        searchPlaceholder: 'Buscar héroe o villano...',
        viewProfile: 'Ver Detalle',
        stats: 'Estadísticas de Poder',
        intelligence: 'Inteligencia',
        strength: 'Fuerza',
        speed: 'Velocidad',
        durability: 'Durabilidad',
        power: 'Poder',
        combat: 'Combate',
        allPublishers: 'Todas las Editoriales',
        allAlignments: 'Todos los Bandos',
        good: 'Héroe',
        bad: 'Villano',
        neutral: 'Neutral',
        addToTeam: 'Añadir al Equipo',
        removeFromTeam: 'Quitar del Equipo',
        myTeamTitle: 'Mi Equipo Personalizado',
        emptyTeam: 'Aún no has reclutado a nadie para tu equipo.',
        realName: 'Nombre Real',
        placeOfBirth: 'Lugar de Nacimiento',
        firstAppearance: 'Primera Aparición',
        close: 'Cerrar'
    },
    en: {
        title: 'HeroVerse Multiverse',
        searchPlaceholder: 'Search hero or villain...',
        viewProfile: 'View Details',
        stats: 'Power Stats',
        intelligence: 'Intelligence',
        strength: 'Strength',
        speed: 'Speed',
        durability: 'Durability',
        power: 'Power',
        combat: 'Combat',
        allPublishers: 'All Publishers',
        allAlignments: 'All Alignments',
        good: 'Hero',
        bad: 'Villain',
        neutral: 'Neutral',
        addToTeam: 'Add to Team',
        removeFromTeam: 'Remove from Team',
        myTeamTitle: 'My Custom Team',
        emptyTeam: 'You haven\'t recruited anyone to your team yet.',
        realName: 'Real Name',
        placeOfBirth: 'Place of Birth',
        firstAppearance: 'First Appearance',
        close: 'Close'
    }
}